export const selectTheme = {
  select: {
    defaultProps: {
      variant: "outlined",
      color: "white",
      size: "md",
      label: "",
      error: false,
      success: false,
      arrow: undefined,
      value: undefined,
      onChange: undefined,
      selected: undefined,
      offset: 5,
      dismiss: {},
      animate: {
        unmount: {},
        mount: {},
      },
      autoHeight: false,
      lockScroll: false,
      labelProps: {
        className: "text-gray-500",
      },
      menuProps: {},
      className: "",
      disabled: false,
      containerProps: undefined,
    },
    valid: {
      variants: ["standard", "outlined", "static"],
      sizes: ["md", "lg"],
      colors: [
        "blue-gray",
        "gray",
        "brown",
        "deep-orange",
        "orange",
        "amber",
        "yellow",
        "lime",
        "light-green",
        "green",
        "teal",
        "cyan",
        "light-blue",
        "blue",
        "indigo",
        "deep-purple",
        "purple",
        "pink",
        "red",
      ],
    },
    styles: {
      base: {
        container: {
          position: "relative",
          width: "w-[250px]",
          minWidth: "min-w-[200px]",
        },
        select: {
          peer: "peer",
          width: "w-full",
          height: "h-full",
          bg: "bg-transparent",
          color: "text-white",
          fontFamily: "font-inter",
          fontWeight: "font-normal",
          textAlign: "text-left",
          outline: "outline-none focus:outline-none",
          disabled:
            "disabled:bg-gray-800 disabled:border-0 disabled:text-gray-500",
          transition: "transition-all",
        },
        arrow: {
          initial: {
            display: "grid",
            placeItems: "place-items-center",
            position: "absolute",
            top: "top-2/4",
            right: "right-2",
            pt: "pt-px",
            width: "w-5",
            height: "h-5",
            color: "text-gray-400",
            transform: "rotate-0 -translate-y-2/4",
            transition: "transition-all",
          },
          active: {
            transform: "rotate-180",
            mt: "mt-px",
          },
        },
        label: {
          display: "flex",
          width: "w-full",
          height: "h-full",
          userSelect: "select-none",
          pointerEvents: "pointer-events-none",
          position: "absolute",
          left: "left-0",
          fontWeight: "font-normal",
          transition: "transition-all",
          color: "text-white",
        },
        menu: {
          width: "w-full",
          maxHeight: "max-h-96",
          bg: "bg-black",
          p: "p-3",
          border: "border border-gray-400-40",
          borderRadius: "rounded-md",
          boxShadow: "shadow-lg shadow-gray-900/20",
          fontFamily: "font-inter",
          fontSize: "text-sm",
          fontWeight: "font-normal",
          color: "text-normal",
          overflow: "overflow-auto",
          outline: "focus:outline-none",
        },
        option: {
          initial: {
            pt: "pt-[9px]",
            pb: "pb-2",
            px: "px-3",
            borderRadius: "rounded-md",
            lightHeight: "leading-tight",
            cursor: "cursor-pointer",
            userSelect: "select-none",
            background: "hover:bg-gray-700 focus:bg-gray-700",
            opacity: "hover:bg-opacity-80 focus:bg-opacity-80",
            color: "hover:text-white focus:text-white",
            outline: "outline-none",
            transition: "transition-all",
          },
          active: {
            bg: "bg-gray-700 bg-opacity-80",
            color: "text-white",
          },
          disabled: {
            opacity: "opacity-50",
            cursor: "cursor-not-allowed",
            userSelect: "select-none",
            pointerEvents: "pointer-events-none",
          },
        },
      },
    },
  },
};
