import type { Metadata } from "next";
import { Provider } from "jotai";
import { Inter, Open_Sans, Montserrat } from "next/font/google"; // Import Google Fonts
import "./globals.css";
import ThemeProvider from "@/components/theme";
import QueryProvider from "@/components/query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const interFont = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "900"],
});
const openFont = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
  weight: ["300", "800"],
});
const monseFont = Montserrat({
  subsets: ["latin"],
  variable: "--font-monse",
  weight: ["100", "900"],
});

export const metadata: Metadata = {
  title: "Loyalty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} ${openFont.variable} ${monseFont.variable} antialiased`}
      >
        <Provider>
          <QueryProvider>
            <ReactQueryDevtools initialIsOpen={false} />
            <ThemeProvider>{children}</ThemeProvider>
          </QueryProvider>
        </Provider>
      </body>
    </html>
  );
}
