import type { Metadata } from "next";
import { Provider } from "jotai"; // Import Jotai Provider
import "./globals.css";
import localFont from "next/font/local";

const interFont = localFont({
  src: "../static/fonts/Inter-VariableFont_opsz,wght.ttf",
  variable: "--font-inter",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Loyaty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interFont.variable} antialiased`}>
        <Provider>{children}</Provider>{" "}
      </body>
    </html>
  );
}
